# Dockerfile backend (simple)
FROM python:3.11-slim

WORKDIR /app

# Copier le code
COPY app/backend/ /app/

# Installer dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer port
EXPOSE 5000

# Lancer l'app Flask
CMD ["python", "main.py"]
