# Dockerfile frontend (simple)
FROM nginx:alpine

# Copier les fichiers statiques
COPY app/frontend/ /usr/share/nginx/html/

# Copier la config Nginx minimale pour proxy /api
COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
